[profile.default]
via-ir = false
libs = ["lib"]
fs_permissions = [
    { access = "read", path = "./broadcast/DeployMorpho.sol/"},
    { access = "read", path = "./script/morpho/config/"},
    { access = "read", path = "./script/oracles/config/"},
    { access = "read", path = "./script/bundlers/config/"},
    { access = "read", path = "./script/metamorpho-factory/config/"},
    { access = "write", path = "./script/morpho/verify.sh"},
    { access = "write", path = "./script/oracles/verify.sh"},
    { access = "write", path = "./script/bundlers/verify.sh"},
    { access = "write", path = "./script/metamorpho-factory/verify.sh"},
    { access = "read", path = "./lib/morpho-blue/out/"},
    { access = "read", path = "./lib/morpho-blue-irm/out/"},
    { access = "read", path = "./lib/morpho-blue-oracles/out/"},
    { access = "read", path = "./lib/morpho-blue-bundlers/out/"},
    { access = "read", path = "./lib/metamorpho/out/"}
]

[profile.default.fmt]
wrap_comments = true

[profile.default.rpc_endpoints]
custom = "${RPC_URL}"
ethereum = "https://eth-mainnet.g.alchemy.com/v2/${ALCHEMY_KEY}"
goerli = "https://eth-goerli.g.alchemy.com/v2/${ALCHEMY_KEY}"
sepolia = "https://eth-sepolia.g.alchemy.com/v2/${ALCHEMY_KEY}"


[profile.build]
via-ir = true
test = "/dev/null"
script = "/dev/null"


[profile.test]
ffi = true
via-ir = false


[profile.script]
via-ir = true
src = "/dev/null"
test = "/dev/null"


# See more config options https://github.com/foundry-rs/foundry/tree/master/crates/config
